# Generated by Django 4.1.3 on 2022-12-05 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='tegnology',
            new_name='technology',
        ),
    ]
